---
- name: Create Kibana directory
  file:
    path: /home/{{default_user}}/kibana/
    state: directory  

- name: Kibana config file
  template:
    src: kibana.yml.j2
    dest: /home/{{default_user}}/kibana/kibana.yml    

- name: Kibana
  docker_container:
    name: "kibana"
    hostname: "{{HOSTNAME}}"
    image: "{{IMAGE}}:{{BUILD}}"
    pull: "true"
    network_mode: host 
    recreate: "yes"
    state: "started"
    log_driver: "{{DOCKER_LOG_DRIVER}}"
    log_options: "{{DOCKER_LOG_OPTIONS}}"
    restart_policy: "unless-stopped"
    volumes:
      - /home/{{default_user}}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  when: DOCKER_NETWORK_MODE == 'host'

- name: Kibana
  docker_container:
    name: "kibana"
    hostname: "{{HOSTNAME}}"
    image: "{{IMAGE}}:{{BUILD}}"
    pull: "true"
    network_mode: bridge 
    recreate: "yes"
    state: "started"
    log_driver: "{{DOCKER_LOG_DRIVER}}"
    log_options: "{{DOCKER_LOG_OPTIONS}}"
    restart_policy: "unless-stopped"
    published_ports:
     - "0.0.0.0:5601:5601"
    volumes:
      - /home/{{default_user}}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  when: DOCKER_NETWORK_MODE == 'bridge'
